### ISSUE TITLE
ZenHub設定

### ISSUE THREAD

**Issue by miyukin** [miyukin/tamagopiyo#1]
ＺｅｎＨｕｂ設定したよ

**Comment by miyukin** [comment]
ＺｅｎＨｕｂの設定方法
１．https://www.zenhub.io/　にアクセス
２．「ＳＩＮＧ　ＵＰ　ＮＯＷ」ボタンを押下
３．GitHubの画面右上に「ZH」と表示される
４．右の「｜｜｜」　Boardをクリック！

**Comment by ototadana** [comment]
ありがとう！
できました。
